---

repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks.git
   rev: v4.2.0   # ok python3.6 on Ubuntu 18.04 AND python3.7 on Ubuntu 19.04 AND python3.8 on Ubuntu 20.04
   hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
      args: ['--maxkb=123']
      exclude: >
                (?x)^(
                    .pnp.cjs|
                    package-lock.json|
                    petclinic-native_latest.tar.gz|
                )$
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
      exclude: >
                (?x)^(
                    .mvn/|
                )$
    - id: check-json
      exclude: ^.vscode/
    - id: check-xml
    - id: check-yaml
    - id: check-symlinks
    - id: check-merge-conflict
    - id: debug-statements
      exclude: ^.cache/
    - id: detect-private-key
      exclude: >
                (?x)^(
                    README.md|
                    .ssh/id_rsa|
                    roles/jenkins-master/defaults/main.yml|
                    roles/jenkins-master/README.md
                )$
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: file-contents-sorter
 - repo: https://github.com/pre-commit/mirrors-autopep8
   rev: v1.6.0
   hooks:
    - id: autopep8
 - repo: https://gitlab.com/pycqa/flake8
   rev: 3.9.2
   hooks:
    - id: flake8
      args: [--max-line-length=120]
  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  #   rev: v1.1.6
  #   hooks:
  #    - id: remove-crlf
  #    - id: remove-tabs
  #      args: [ --whitespaces-count, 2 ]
 - repo: https://github.com/pre-commit/pre-commit.git
   rev: v2.19.0
   hooks:
    - id: validate_manifest
 - repo: https://github.com/asottile/reorder_python_imports.git
   rev: v3.1.0
   hooks:
    - id: reorder-python-imports
      exclude: ^.cache/
  #    language_version: python3
  #    language_version: python2.7
 - repo: https://github.com/asottile/add-trailing-comma
   rev: v2.2.3
   hooks:
    - id: add-trailing-comma
 - repo: https://github.com/willthames/ansible-lint.git
   rev: v6.2.1
   hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
      exclude: '.travis.yml'
 - repo: https://github.com/doublify/pre-commit-hindent.git
   rev: b3680b6ebf9f7cf29b19307f246adef66756feef
   hooks:
    - id: hindent
 - repo: https://github.com/detailyang/pre-commit-shell
   rev: 1.0.5
   hooks:
    - id: shell-lint
      # entry: pre_commit_hooks/shell-lint.sh -x
      args: [-x]
      exclude: >
                (?x)^(
                    mvnw|
                    hooks|
                    test/init.sh|
                    test/test.sh
                )$
 - repo: https://github.com/asottile/pyupgrade
   rev: v2.32.1
   hooks:
    - id: pyupgrade
 - repo: https://github.com/pre-commit/mirrors-autopep8
   rev: v1.6.0
   hooks:
    - id: autopep8
 - repo: https://github.com/PyCQA/bandit
   rev: 1.7.4
   hooks:
    - id: bandit
      exclude: >
                (?x)^(
                    versioneer.py|
                    hooks/_version.py|
                    hooks/test/|
                )$
 - repo: https://github.com/IamTheFij/ansible-pre-commit
   rev: v0.1.2
   hooks:
    - id: encryption-check
 - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
   rev: v1.1.2
   hooks:
  # -   id: htmlhint
  #   # optional custom config:
  #   args: [--config, .htmlhintrc]
    - id: htmllint
    - id: markdown-toc
      args: [--maxdepth, "3", -i]
    - id: dockerfile_lint
      # optional custom config:
      args: [--json, --verbose, --dockerfile]
